name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_TARGET_PLATFORM: linux/amd64,linux/arm64
      REPO_NAME: ${{github.event.repository.name}}
      IMAGE_TAG: ${{github.ref_name}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo "docker_platform=${DOCKER_TARGET_PLATFORM}" >> $GITHUB_OUTPUT
          echo "docker_image=${DOCKER_USERNAME}/${REPO_NAME}" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build and push
        if: success()
        run: |
          docker login && \
          docker buildx build \
          --platform ${{steps.prepare.outputs.docker_platform}} \
          --tag ${{steps.prepare.outputs.docker_image}}:$IMAGE_TAG \
          --push .